import React from "react";
import { Link } from "@reach/router";
import { makeStyles } from "@material-ui/core";
import Divider from "@material-ui/core/Divider";
import ArrowBackIosIcon from "@material-ui/icons/ArrowBackIos";

const useStyles = makeStyles(theme => ({
  linkBack: {
    color: "#202020",
    fontSize: "1.8rem",
    fontWeight: 530,
    display: "flex",
    alignItems: "center",
    marginBottom: "1.6rem",
    marginLeft: "0.3rem",
    textDecoration: "none",
  },
  main: {
    width: "80%",
    margin: "0 auto",
    "& h3": {
      fontSize: "1.8rem",
      width: "16rem",
      margin: "0 auto",
      textAlign: "center",
    },
    "& h4": {
      fontSize: "1.6rem",
      marginBottom: "0",
    },
    "& h5": {
      fontSize: "1.5rem",
      marginBottom: "0",
    },
    "& p": {
      fontSize: "1.4rem",
      marginTop: "0",
    },
    "& ol, ul, li": {
      fontSize: "1.4rem",
    },
  },
  a11yLink: {
    fontSize: "1.8rem",
    color: "#2962FF",
    textDecoration: "underline",
  },
}));

export default function PrivacyPolicy() {
  const classes = useStyles();
  return (
    <main className={classes.main}>
      <Link to={`/`} className={classes.linkBack}>
        <ArrowBackIosIcon color="primary" fontSize="large" />
        Go Back
      </Link>
      <Divider variant="inset" className={classes.divider} />
      <h3>Privacy Policy Effective Date: June 30, 2020</h3>
      <p>
        Angel City Sports values your privacy and believes that protecting and
        securing the personal information that we collect from our users is one
        of our most important responsibilities. This privacy policy details the
        types of personal information we collect and record, how we use it and
        the options you have for managing your privacy on our site. We welcome
        your questions and comments on this policy, you can e-mail us at
        camille@angelcitysports.
      </p>
      <p>
        Angel City Sports operates the Angel City Sports.org website and the
        Angel City Sports mobile application. We use your data to provide and
        improve our website and application (“Services”) and to improve your
        experience while using the Services. All of our Services are governed by
        this Privacy Policy.
      </p>
      <p>By using the Services, you hereby consent to this Privacy Policy.</p>
      <p>
        Our mission is to provide you with an optimal experience while visiting
        Angel City Sports on the website or application. To do that, we
        customize the website and application using information that you provide
        and information that we collect. Angel City Sports collects some
        information from when you: (a) create an account; (b) create user
        generated content; (c) watch advertisements within our Services (d)
        contact Angel City Sports customer service and take part in
        technical-support sessions; (e) chat with other users of the Services;
        (f) share or contribute to our social media channels and other community
        websites; or (g) apply for a job.
      </p>
      <p>
        Usage Data is data collected automatically either generated by the use
        of the website or application or from the website or application
        infrastructure itself. Usage Data may include information such as your
        computer’s Internet Protocol address (e.g. IP address), browser type,
        browser version, the pages of our service that you visit, the time and
        date of your visit, the time spent on those pages, unique device
        identifiers and other diagnostic data. When accessing Angel City Sports
        via a mobile device, Usage Data may also include your mobile device
        unique ID, IP address of your mobile device, your mobile operating
        system, the type of mobile internet browser you use, unique device
        identifiers and other diagnostic data.
      </p>
      <p>
        In addition to the Usage Data, Angel City Sports collects data used for
        customization of your experience based upon your specific information
        and needs, Customization Data. Customization Data includes information
        you may give us such as your name, e-mail address, birthdate or other
        personal information. In addition, you may opt in so that we may collect
        information on interaction with websites including eye gaze – reaction
        to lights and images, eye movement and head movement so as to adapt to
        your use of the website.
      </p>
      <h4>USE OF DATA</h4>
      <p>Angel City Sports uses the collected data to:</p>
      <ul>
        <li>Provide and maintain the website and application</li>
        <li>Notify you about changes to our services</li>
        <li>
          Allow you to participate in interactive features on our website and
          application when you choose to do so
        </li>
        <li>Provide customer support</li>
        <li>
          Gather analysis or valuable information so that we can improve our
          website and application
        </li>
        <li>Monitor the usage of our website and application</li>
        <li>Detect, prevent and address technical issues</li>
        <li>Provide you with news from Angel City Sports</li>
      </ul>
      <h4>Retention of Data</h4>
      <p>
        We will retain your Customization Data only for as long as is necessary
        for the purposes set out in this Privacy Policy. We will retain and use
        your Customization Data to the extent necessary to comply with our legal
        obligations (for example, if we are required to retain your data to
        comply with applicable laws), resolve disputes and enforce our legal
        agreements and policies.
      </p>
      <p>
        We will also retain Usage Data for internal analysis purposes. Usage
        Data is generally retained for shorter periods of time, except when this
        data is used to strengthen the security or to improve the functionality
        of our services, or we are legally obligated to retain this data for
        longer periods.
      </p>
      <h4>Transfer of Data</h4>
      <p>
        Your information, including personal data, may be transferred to and
        maintained on computers located outside your state, province, country or
        other governmental jurisdiction where the data protection laws differ
        from those in your jurisdiction. If you are located outside the United
        States and choose to provide information to us, please note that we
        transfer the data, including Personal Data, to the United States and
        process it here. Your consent to this Privacy Policy followed by your
        submission of such information represents your agreement to that
        transfer. We will take all steps reasonably necessary to ensure that
        your data is treated securely and in accordance with this Privacy Policy
        and no transfer of your Personal Data will take place to an organization
        or a country unless there are adequate controls in place including the
        security of your data and other personal information.
      </p>
      <h4>Disclosure of Data</h4>
      <p>
        Under certain circumstances, we may disclose your personal data. If we
        are involved in a merger, acquisition or asset sale, your Personal Data
        may be transferred. We will provide notice before your Personal Data is
        transferred and becomes subject to a different Privacy Policy.
      </p>
      <p>
        We only share information with law enforcement agencies or government
        agencies if we believe that disclosure is reasonably necessary to comply
        with a law, regulation or legal request; to protect the safety, rights,
        or property of the public, any person, or Angel City Sports; or to
        detect, prevent, or otherwise address fraud, security or technical
        issues.
      </p>
      <h4>Children</h4>
      <p>
        We encourage parents and guardians to teach their children about privacy
        and how their information may be used on the Internet. Children should
        never disclose their name, address or phone number, or any personal
        information, without their parents’ or guardian’s prior permission.
      </p>
      <p>
        We consider a user to be a child if they are under the age of 13, unless
        more stringent regulations applies in their state of residence.
      </p>
      <p>
        If we consider that any of our Services are directed at users under the
        age of the minimum legal age required in their country of residence, we
        can block such users from using the Services or from providing
        information and/ or limit the collection of information from such users
        as described below in more detail.
      </p>
      <p>
        No personal information should be submitted to Angel City Sports by
        users under the minimum legal age required in their state of residence.
        We apply the following limitations to personal information collection
        for a user that is not of the minimum legal age required in their state
        of residence.
      </p>
      <h4>Such a user cannot:</h4>
      <ul>
        <li>Display their real name or any information</li>
        <li>Access chat, leaderboards, forums, SNS</li>
        <li>Subscribe to services</li>
        <li>
          Use any other feature where users could appear under their real names
        </li>
      </ul>
      <p>
        With respect to such a user, we will prevent the collection and use of
        their precise geolocation data and display to them contextual
        advertising only.
      </p>
      <p>
        Children can be invited to take part in testing the application with
        their parents’ or guardians’ authorization and/ or their parents’ or
        guardians’ physical presence being required depending on the state where
        the testing is conducted.
      </p>
      <p>
        Parent must exercise their privacy rights for their children. Please
        refer to “Your rights” section of this Privacy Policy.
      </p>
      <h4>Security of Data</h4>
      <p>
        Keeping your data safe is extremely important to us. However, no
        transmission over the internet or method of electronic storage is 100%
        secure. We strive to use commercially acceptable means to protect your
        Personal Data, we cannot guarantee absolute security.
      </p>
      <h4>California Users</h4>
      <ul>
        <li>
          <h4>
            Our Policy on “Do Not Track” Signals under the California Online
            Protection Act (CalOPPA)
          </h4>{" "}
          We do not support the Do Not Track browser setting and you can learn
          more about how it affects our collection. The browser you use lets you
          control cookies or other types of local data storage.
        </li>
        <li>
          <h4>The California Consumer Privacy Act of 2018 (CCPA)</h4> permits
          California residents to request from a business, with whom the
          California Resident has an established business relationship, certain
          information about the types of personal information the business has
          collected, shared with, and/ or sold to third parties for a business
          or commercial purpose during the immediately preceding calendar year.
        </li>
      </ul>
      <h4>
        Your Data Protection Rights under the General Data Protection Regulation
        (GDPR)
      </h4>
      <p>
        If you are a resident of the European Economic Area (EEA), you have
        certain data protection rights. Angel City Sports aims to take
        reasonable steps to allow you to correct, amend, delete or limit the use
        of your Personal Data. If you wish to be informed about what Personal
        Data we hold about you and if you want to be removed from our system,
        please contact us at info@adaptiveapps.com.
      </p>
      <h4>Your Rights</h4>
      <p>
        We ask that you keep the information that you provide to us updated. You
        can correct any information you have provided by contacting us through
        this form opt-in@angelcitysports.org.
      </p>
      <p>
        You represent and warrant that all information you provide us is true
        and correct and relates to you and not to any other person.
      </p>
      <p>
        You can exercise your rights at any time and ask Angel City Sports for
        access to, rectification or erasure of, your information.
      </p>
      <p>
        Please note that other third parties (our data partners) may be
        controllers of your information. You can obtain more details and opt out
        of the sharing of your personal information to third parties for any
        purpose by contacting us opt-in@adaptivapps.org.
      </p>
      <p>
        If you have previously consented to any direct marketing communications
        from us or subscribed to our newsletters, you can unsubscribe by
        clicking on a link available in each communication and newsletter sent
        to you.
      </p>
      <p>
        If you want to decline to allow cookies or other tracking technologies,
        please read our Cookies Policy in this Privacy Policy.
      </p>
      <p>
        Please note that Mobile App functionality can be affected by your
        actions. Some of your information and its processing is mandatory for
        Angel City Sports to provide the Services.
      </p>
      <p>
        If you withdraw your consent or ask for the deletion of your
        information, we will not use or process your information anymore but we
        will store it to answer regulatory or government requests. We also
        reserve the right to retain an archive of such information for a
        commercially reasonable time to ensure that its deletion does not affect
        the integrity of our data; and we further reserve the right to retain an
        anonymous version of such information.
      </p>
      <p>
        To preserve the confidentiality of your information, when you contact us
        to make corrections, we must be able to correctly identify you. For this
        reason, please provide us with a copy of any official document to prove
        your identity. This copy will be safely destroyed within two months of
        your request being received and closed.
      </p>
      <p>
        Our team will look into your request and answer you within one month,
        unless your request requires further investigation. You’ll be
        specifically informed if that is the case.
      </p>
      <h4>Service Providers</h4>
      <p>
        We may employ third party companies and individuals to assist in the
        development of our website and application. Such third parties may have
        access to your Personal Data for the purpose of assisting us and are
        obligated not to disclose or use your Personal Data for any other
        purpose.
      </p>
      <h4>Analytics</h4>
      <p>
        We may use third-party Service Providers to monitor and analyze the use
        of our website or application.
      </p>
      <p>
        Google Analytics: Google Analytics is a web analytics service offered by
        Google that tracks and reports website traffic. Google uses the data
        collected to track and monitor the use of website and application. This
        data is shared with other Google services. Google may use the collected
        data to contextualize and personalize the ads of its own advertising
        network. For more information on the privacy practices of Google, please
        visit the Google Privacy & Terms web page:
        https://policies.google.com/privacy.
      </p>
      <p>
        Google Ads (AdWords) remarketing services is provided by Google Inc. –
        you can opt out of Google Analytics for Display Advertising and
        customize the Google Display Network ads by visiting Google Ads Setting:
        https://adssettings.google.com/authenticated.
      </p>
      <p>
        Google also recommends installing the Google Analytics Opt-Out Browser
        Add-on https://tools.google.com/dlpage/gaoptout for your web browser.
        Google Analytics Opt out Browser Add-on provides visitors with the
        ability to prevent their data from being collected and used by Google
        Analytics.
      </p>
      <h4>Links to Other Sites</h4>
      <p>
        Our website and application may contain links to other sites that are
        not operated by us. If you click on a third party link, you will be
        directed to that third party’s site. We strongly advise you to review
        the Privacy Policy of every site you visit. We have no control over and
        assume no responsibility for the content, privacy policies or practices
        of any third party sites or services.
      </p>
      <h4>Changes to this Privacy Policy</h4>
      <p>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page. We will
        let you know via email and or prominent notice on our website or
        application, prior to the change becoming effective and update the
        “effective date” at the top of this Privacy Policy. Please review this
        Privacy Policy periodically for any changes. Changes to this Privacy
        Policy are effective when they are posted on this page.
      </p>
      <h4>Legal Disclaimer</h4>
      <p>
        Our services operate AS IS, and we do not represent or warrant that our
        Services will be available at all times, or that your use of the
        Services will be uninterrupted or error-free. WE are not responsible for
        your ability to access the Services or matters beyond our control. This
        <p>
          Privacy Policy is governed by the laws of the state of California. Any
          dispute arising from the use of the Services shall be submitted to the
          competent courts in the county of Los Angeles, CA.
        </p>
      </p>
      <h5>
        If you have any questions about the Privacy Policy, please contact us by
        email at camille@angelcitysports.
      </h5>
    </main>
  );
}
